"""
UI theme constants for PDF Merger application.
Light blue theme.
"""

# Layout (px)
CORNER_RADIUS = 12
INPUT_RADIUS = 8
CARD_PADDING = 20
SECTION_SPACING = 20
CARD_SPACING = 10
SUMMARY_CARD_SPACING = 16
LABEL_INPUT_SPACING = 12
CONTENT_MAX_WIDTH = 1000
METRIC_CARD_PADDING = 16

# Colors (light blue theme)
APP_BACKGROUND = "#F0F4FF"
CARD_BACKGROUND = "#FFFFFF"
CARD_BORDER = "#C7D7F5"
INPUT_BACKGROUND = "#EEF2FF"
PRIMARY_BLUE = "#2563EB"
PRIMARY_BLUE_HOVER = "#1D4ED8"
SUCCESS_GREEN = "#16A34A"
WARNING_YELLOW = "#D97706"
ERROR_RED = "#DC2626"
TEXT_PRIMARY = "#1E293B"
TEXT_SECONDARY = "#64748B"

# Aliases for backward compatibility
BG_DARK = APP_BACKGROUND
CARD_BG = CARD_BACKGROUND
INPUT_CONTAINER_BG = INPUT_BACKGROUND
INPUT_BG = INPUT_BACKGROUND
LOG_BG = "#F8FAFC"
FOCUS_BLUE = PRIMARY_BLUE
INPUT_HOVER_BG = "#DBEAFE"
GREEN_SUCCESS = SUCCESS_GREEN
RED_ERROR = ERROR_RED
YELLOW_WARNING = WARNING_YELLOW
BLUE_INFO = TEXT_SECONDARY

# Results mini-card
METRIC_CARD_BG = "#EEF2FF"

# Typography
FONT_TITLE_SIZE = 28
FONT_SECTION_SIZE = 18
FONT_LABEL_SIZE = 14
FONT_HELPER_SIZE = 12
FONT_MONO_SIZE = 12
FONT_METRIC = 30
FONT_SUMMARY_NUMBER = FONT_METRIC
